# Generated by Django 5.0.4 on 2024-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdate',
            name='close_month',
        ),
        migrations.RemoveField(
            model_name='applicationdate',
            name='close_year',
        ),
        migrations.RemoveField(
            model_name='applicationdate',
            name='open_month',
        ),
        migrations.RemoveField(
            model_name='applicationdate',
            name='open_year',
        ),
        migrations.AlterField(
            model_name='applicationdate',
            name='close_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='applicationdate',
            name='open_date',
            field=models.DateField(),
        ),
    ]
