# Generated by Django 5.0.4 on 2024-04-22 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_applicationdate_close_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='recruitment.applicant'),
        ),
    ]
