# Generated by Django 5.0.4 on 2024-04-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_rename_county_of_birth_applicant_county_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantdocument',
            old_name='ccgpa',
            new_name='cgpa',
        ),
        migrations.RenameField(
            model_name='employeedocument',
            old_name='ccgpa',
            new_name='cgpa',
        ),
        migrations.RenameField(
            model_name='pypdocument',
            old_name='ccgpa',
            new_name='cgpa',
        ),
    ]
