# Generated by Django 5.0.4 on 2024-04-25 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_applicant_gender_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantdocument',
            name='id',
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document', serialize=False, to='recruitment.applicant'),
        ),
    ]
