# Generated by Django 5.0.4 on 2024-05-09 20:37

import django.core.validators
import recruitment.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_remove_applicantdocument_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='application_letter',
            field=models.FileField(upload_to=recruitment.utilities.emp_application_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='community_letter',
            field=models.FileField(upload_to=recruitment.utilities.emp_community_letter_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='degree',
            field=models.FileField(upload_to=recruitment.utilities.emp_degree_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='reference_letter',
            field=models.FileField(upload_to=recruitment.utilities.emp_reference_letter_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='resume',
            field=models.FileField(upload_to=recruitment.utilities.emp_resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
