# Generated by Django 5.0.6 on 2024-06-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_alter_employee_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstagecompletedaudittrial',
            name='application_stage',
        ),
        migrations.RemoveField(
            model_name='applicationstagecompletedaudittrial',
            name='employee',
        ),
        migrations.DeleteModel(
            name='ApplicantStatusAuditTrial',
        ),
        migrations.DeleteModel(
            name='ApplicationStageCompletedAuditTrial',
        ),
    ]
