# Generated by Django 5.0.6 on 2024-06-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_remove_applicant_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
