# Generated by Django 5.0.6 on 2024-06-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_applicant_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantstatus',
            name='process_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='recruitment.employee'),
        ),
    ]
