# Generated by Django 5.0.6 on 2024-06-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_alter_applicantstatus_process_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstage',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Under review', 'Under review'), ('Pending', 'Pending'), ('Unsuccessful', 'Unsuccessful'), ('Successful', 'Successful')], max_length=13)),
                ('rejection_reason', models.CharField(blank=True, choices=[('Police clearance', 'Police clearance'), ('National id', 'National ID'), ('Diploma', 'Diploma'), ('Transcript', 'Transcript'), ('Writen exams', 'Written exams'), ('Interview', 'Interview'), ('Job readiness', 'Job readiness'), ('Absent', 'Absent'), ('Document', 'Document'), ('Disorderly conduct', 'Disorderly conduct'), ('Other', 'Other')], max_length=18, null=True)),
                ('other_rejection_reason', models.TextField(blank=True, null=True)),
                ('process_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='recruitment.applicant')),
                ('process_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='recruitment.employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='recruitment.applicationstage')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicantStatus',
        ),
    ]
